modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "createaeronauticscarworks"
version = "0.1.0-BETA"
displayName = "Create Aeronautics: Car Works"
authors = '''fennek (mod lead),
nova (main artist),
bennet (code contributor)
'''
description = '''An addon mod that focus on make general vehicle creation easier

special thanks to all the people that saw carwors born as just a block copying
create diesel generatos small generator to what it is rn love yall xoxo fennek'''

[[mixins]]
config='cacw.mixins.json'

[[dependencies.createaeronauticscarworks]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.219,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createaeronauticscarworks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.createaeronauticscarworks]]
modId="create"
type="required"
versionRange="[6.0.10,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.createaeronauticscarworks]]
modId="sable"
type="required"
versionRange="[1.1.0,3.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.createaeronauticscarworks]]
modId="aeronautics"
type="required"
versionRange="[1.1.0,3.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.createaeronauticscarworks]]
modId = "createdieselgenerators"
type = "required"
versionRange = "[1.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.createaeronauticscarworks]]
modId="simulated"
type="required"
versionRange="[1.1.0,3.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.createaeronauticscarworks]]
modId="offroad"
type="required"
versionRange="[1.1.0,3.0.0)"
ordering="AFTER"
side="BOTH"